---
driver_plugin: vagrant

platforms:
- name: ubuntu-14.04
  driver_config:
    require_chef_omnibus: 11.12.8
    customize:
      cpus: 2
      memory: 384

suites:
- name: default
  run_list:
  - recipe[apt::default]
  - recipe[java::default]
  - recipe[logstash::server]
  - recipe[kibana::default]
  attributes:
    java:
      install_flavor: "oracle"
      jdk_version: "7"
      oracle:
        accept_oracle_download_terms: true
    logstash:
      instance:
        server:
          xms: '256M'
          xmx: '256M'
          config_templates:
            input_syslog: 'config/input_syslog.conf.erb'
            output_stdout: 'config/output_stdout.conf.erb'
            output_elasticsearch: 'config/output_elasticsearch.conf.erb'
          pattern_templates:
            default: 'patterns/custom_patterns.erb'
          elasticsearch_ip: '127.0.0.1'
          enable_embedded_es: true
    kibana:
      webserver_listen: '0.0.0.0'
      webserver: 'nginx'
      install_type: 'file'
